In [3]:
from sklearn.model_selection import KFold
import numpy as np

In [12]:
x = np.random.randn(10,1)
kf = KFold(n_splits=5)
for a,b in kf.split(x):
    print(a,b)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]
